name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Debug Environment Variables
        run: |
            echo "GH_TOKEN: ${{ secrets.GH_TOKEN }}"
            echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

      - name: Debug Semantic Release Output
        run: |
            npx semantic-release --debug

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variable
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "GH_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV

      - name: Run Semantic Release
        run: npx semantic-release

      - name: Push changes
        run: |
          git config user.name "Semantic Release Bot"
          git config user.email "actions@users.noreply.github.com"
          git push --follow-tags
